### PR TITLE
Upgrade the default helm chart values of resource limits and requests

### PR DESCRIPTION
**Pull request by bzon**
This fixes https://github.com/kubernetes-helm/monocular/issues/473

### CODE REVIEW

**Comment by bzon** [comment]
@thelinuxfoundation CLA confirmed

**Comment by prydonius** [comment]
@bzon looks like you're still having issues with the CLA. This might help https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by bzon** [comment]
@prydonius I'm doing the CNCF CLA now. I just realized that I only did the Linux Foundation one.

**Comment by bzon** [comment]
@thelinuxfoundation CNCF CLA signed.

**Comment by prydonius** [comment]
thanks!!

**Pull request merged**
